# Project information
site_name: IITM-ESM Documentation
site_url: https://iitm-esm.github.io/iitm-esm
site_author: ESM group
# Repository
repo_name: iitm-esm
repo_url: https://github.com/iitm-esm/iitm-esm
edit_uri: '' 
docs_dir: src

nav:
  - User Guide: 
    - user_guide/index.md
  - Technical documentation: 
    - tech_docs/index.md
  - Developers Guide: 
    - dev_guide/index.md
  - FAQ: FAQs.md
  
# Theme
theme: 
  name: material
  features: 
    # - navigation.instant
    # - navigation.tabs
    - navigation.indexes
  icon:
    repo: fontawesome/brands/github

# Plugins
plugins:
  - search
  - include-markdown

