name: ci
on:
  push:
    branches:
      - aditi/docs
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install requirements
        working-directory: ./docs
        run: pip install -r requirements.txt
      - name: Make Documentation
        working-directory: ./docs
        run: mkdocs gh-deploy --force